# Generated by Django 5.1.2 on 2024-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('phone', models.CharField(max_length=16, verbose_name='Celular')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
