# Generated by Django 5.1.2 on 2024-12-02 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home_view.pessoafisica')),
                ('buisness_name', models.CharField(max_length=255, verbose_name='Nome do Empreendimento')),
                ('cnpj', models.IntegerField(max_length=14, verbose_name='CNPJ')),
                ('adress', models.CharField(max_length=255, verbose_name='Endereço')),
                ('region', models.CharField(max_length=255, verbose_name='Região')),
                ('buisness_phone', models.CharField(max_length=16, verbose_name='Telefone do Empreendimento')),
                ('buisness_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail do Empreendimento')),
                ('social_media', models.CharField(blank=True, max_length=255, null=True, verbose_name='Redes Sociais')),
            ],
            bases=('home_view.pessoafisica',),
        ),
    ]
