# Generated by Django 5.1.2 on 2024-12-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0002_pessoajuridica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.IntegerField(verbose_name='CNPJ'),
        ),
    ]
